server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
      # encoding 을 UTF-8로 설정
      # 강제로 설정

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    # MySQL을 설정하는 이유는 Maria와 설정이 같이 때문
    # maria를 사용하지만 연결 및 배포는 h2사용
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: create
      properties:
        '[hibernate.default_batch_fetch_size]': 100
        '[hibernate.format_sql]': true
      show-sql: true
    output:
      ansi:
        enabled: always

  logging:
    level:
      '[shop.mtcoding.bank]': DEBUG
      '[org.hibernate.type]': TRACE